name: Summarise Issues

on:
  schedule:
    - cron: '30 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Summarise Issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL_FROM: do_not_reply@mnot.net
        SMTP_HOST: smtp.fastmail.com
        SMTP_USERNAME: mnot@mnot.net
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python3 open_issues.py -e subscribers.json
