name: Summarise Issues

on:
  schedule:
    - cron: '45 */6 * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Fetch repo_data.json
      run: |
        curl https://raw.githubusercontent.com/mnot/ietf-repo-data/master/repo_data.json > repo_data.json
    - name: Summarise Issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENDER_EMAIL: do_not_reply@mnot.net
        SMTP_SERVER: smtp.fastmail.com
        SMTP_USERNAME: mnot@mnot.net
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python3 open_issues.py -e repo_data.json
