name: Validate

on:
  push:
    paths:
    - subscribers.json
  pull_request:
    paths:
    - subscribers.json

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Validate subscribers.json
      run: |
        python3 validate.py subscribers_schema.json subscribers.json
